apiVersion: v1 
kind: Pod
metadata:
  name: testpod
  labels:
    demo: resouce
spec:
  containers:
    - name: con1
      image: nginx
      resources:
        requests:
          memory: 10Mi
          cpu: 10M
        limits: 
          memory: 30M
          cpu: 200M 