apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector: 
    matchLabels:
      name: deployment
  
  template:
    metadata:
      name: mydp 
      labels:
        name: deployment
    spec:
      containers:
        - name: co1
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo CO1; sleep 2; done;"]
