apiVersion: v1
kind: LimitRange
metadata: 
  name: my-limit-range
  namespace: dev-namespace
spec:
  limits:
    - max:
        memory: 1Gi 
      min: 
        memory: 500Mi
      default:
        cpu: 1
        memory: 50m
      defaultRequest:
        cpu: .5
        # here i didn't specify the default request limit for memory, so i'll be same as default limit (here 50m)
      type: Container
