apiVersion: v1
kind: Pod
metadata: 
  name: testpod
  labels:
    name: node-selector
  annotations:
    description: This is for node selector
spec:
  containers:
    - name: co1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello; sleep 2; done;"]
  nodeSelector:         # you can give any name 
    os: ubuntu


