apiVersion: v1
kind: Pod
metadata:
  name: testpod
  annotations:
    description: This is testpod 
spec:
  containers:
    - name: co1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo CO1; sleep 2; done;"]
      env:
        - name: username
          value: DevOps
        - name: password
          value: devops@123

    - name: co2
      image: nginx
      command: ["/bin/bash", "-c", "while true; do echo C02; sleep 2; done;"]
      ports:
        - containerPort: 80
          hostPort: 80
  