apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 3
  selector:
    myname: xyz

  template:
    metadata:
      name: pod1
      labels:
        myname: xyz           # match with selector name
    spec:
      containers:
        - name: co1
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo CO1; sleep 2; done;"]
          # ports:
          #   - containerPort: 80
          #     hostPort: 80

