apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: job
spec: 
  schedule: '* * * * *'
  jobTemplate: 
    spec: 
      template:
        spec: 
          containers:
            - name: con1
              image: ubuntu
              command: ['echo', 'Hello']
          restartPolicy: Never

