---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbits

---
apiVersion: v1
kind: ServiceAccount 
metadata: 
  name: rabbitmq

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq
rules:
  - apiGroups:
      - ""
    resources: 
      - endpoints
    verbs:
      - get
      - list
      - watch 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq
  namespace: rabbits
subjects:
  - kind: ServiceAccount
    name: rabbitmq
    namespace: rabbits
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq

