apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector: 
    matchLabels:
      # name: deployment
      type: app
  template:
    metadata:
      name: mydp 
      labels:
        # name: deployment
        type: app
    spec:
      containers:
        - name: co1
          image: nginx
  