apiVersion: v1
kind: Pod
metadata: 
  name: liveness-probe
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 80
      livenessProbe:
        exec:
          command:
            - curl
            - localhost:80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 10
  