apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

    # Specific secret variable
    env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name:  app-secret
            key:  PASSWORD

    # All secret variable will be there
    envFrom:
      - secretRef:
          name: app-secret
    

volumes:
  - name: app-secret-volume
    secret:
      secretName: app-secret